# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hindu Temples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hindu Temples
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  target 'Hindu TemplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hindu TemplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
